export const TaskData = [
  {
    title: "Building Software Systems",
    name: "Joshua Asiedu",
    deadline: "January, 20th",
    description: "We are building a ui system for bank of ghana",
    progress_rate: "80%",
    status: "In Progress",
    milestone: [
      {
        title: "Create Graphics",
        progress_rate: "20%",
        progress_status: "In Progress",
        amount: "2000",
        payment_status: "Not Paid",
      },
      {
        title: "Video Editor",
        progress_rate: "10%",
        progress_status: "In Progress",
        amount: "None",
        payment_status: "Not Paid",
      },
      {
        title: "System Review",
        progress_rate: "10%",
        progress_status: "In Progress",
        amount: "1200",
        payment_status: "Not Paid",
      },
    ],
  },
  {
    title: "Building Software Systems",
    name: "Joshua Asiedu",
    deadline: "January, 20th",
    description: "We are building a ui system for bank of ghana",
    progress_rate: "80%",
    status: "In Progress",
    milestone: [
      {
        title: "Create Graphics",
        progress_rate: "20%",
        progress_status: "In Progress",
        amount: "2000",
        payment_status: "Not Paid",
      },
      {
        title: "Video Editor",
        progress_rate: "10%",
        progress_status: "In Progress",
        amount: "None",
        payment_status: "Not Paid",
      },
      {
        title: "System Review",
        progress_rate: "10%",
        progress_status: "In Progress",
        amount: "1200",
        payment_status: "Not Paid",
      },
    ],
  },
  {
    title: "Building Software Systems",
    name: "Joshua Asiedu",
    deadline: "January, 20th",
    description: "We are building a ui system for bank of ghana",
    progress_rate: "80%",
    status: "In Progress",
    milestone: [
      {
        title: "Create Graphics",
        progress_rate: "20%",
        progress_status: "In Progress",
        amount: "2000",
        payment_status: "Not Paid",
      },
      {
        title: "Video Editor",
        progress_rate: "10%",
        progress_status: "In Progress",
        amount: "None",
        payment_status: "Not Paid",
      },
      {
        title: "System Review",
        progress_rate: "10%",
        progress_status: "In Progress",
        amount: "1200",
        payment_status: "Not Paid",
      },
    ],
  },
];
