export const COMPANYPROFILEDATA = {
  fieldDetail: [
    {
      id: 1,
      name: "company_name",
      label: "Company Name",
      type: "text",
      placeholder: "Comfee Ghana",
      icon: "fs-input-icon fa fa-user",
    },
    {
      id: 2,
      name: "phone_no",
      label: "Phone",
      type: "text",
      placeholder: "(251) 1234-456-7890",
      icon: "fs-input-icon fa fa-phone-alt",
    },
    {
      id: 3,
      name: "email",
      label: "Email Address",
      type: "text",
      placeholder: "Devid@example.com",
      icon: "fs-input-icon fa fa-envelope",
    },
    {
      id: 4,
      name: "website",
      label: "Website",
      type: "text",
      placeholder: "https://...",
      icon: "fs-input-icon fa fa-globe-americas",
    },
    {
      id: 5,
      name: "sector",
      label: "Sector",
      type: "text",
      placeholder: "Software Engineer",
      icon: "fs-input-icon fa fa-sort-numeric-up",
    },
    {
      id: 6,
      name: "address",
      label: "Address",
      type: "text",
      placeholder: "Boulevard street",
      icon: "fs-input-icon fa fa-globe-americas",
    },
    {
      id: 7,
      name: "est_date",
      label: "Est. Date",
      type: "date",
      placeholder: "Since...",
      icon: "fs-input-icon fa fa-globe-americas",
    },
    {
      id: 8,
      name: "description",
      label: "Descritpion",
      type: "text",
      placeholder: "",
    },
  ],
};
