import { publicUser } from "./route-names";

export const JOBLISTDATA = [
  {
    id: 1,
    img: "https://via.placeholder.com/150",
    duration: "1 days ago",
    location: "Independence Avenue No. 10, Accra, Greater Accra Region, Ghana",
    link: publicUser.jobs.DETAIL1,
    title: "Junior Web Designer",
    noOfBid: "10",
    amount: "₵2000 - ₵3000",
    skills: [
      "ux writing",
      "wire framing",
      "prototyping",
      "information architecture",
    ],
  },
  {
    id: 2,
    img: "https://via.placeholder.com/150",
    duration: "1 days ago",
    location: "Independence Avenue No. 10, Accra, Greater Accra Region, Ghana",
    link: publicUser.jobs.DETAIL1,
    title: "Junior Web Designer",
    noOfBid: "10",
    amount: "₵2000 - ₵3000",
    skills: [
      "ux writing",
      "wire framing",
      "prototyping",
      "information architecture",
    ],
  },
  {
    id: 3,
    img: "https://via.placeholder.com/150",
    duration: "1 days ago",
    location: "Independence Avenue No. 10, Accra, Greater Accra Region, Ghana",
    link: publicUser.jobs.DETAIL1,
    title: "Junior Web Designer",
    noOfBid: "10",
    amount: "₵2000 - ₵3000",
    skills: [
      "ux writing",
      "wire framing",
      "prototyping",
      "information architecture",
    ],
  },
  {
    id: 4,
    img: "https://via.placeholder.com/150",
    duration: "1 days ago",
    location: "Independence Avenue No. 10, Accra, Greater Accra Region, Ghana",
    link: publicUser.jobs.DETAIL1,
    title: "Junior Web Designer",
    noOfBid: "10",
    amount: "₵2000 - ₵3000",
    skills: [
      "ux writing",
      "wire framing",
      "prototyping",
      "information architecture",
    ],
  },
  {
    id: 5,
    img: "https://via.placeholder.com/150",
    duration: "1 days ago",
    location: "Independence Avenue No. 10, Accra, Greater Accra Region, Ghana",
    link: publicUser.jobs.DETAIL1,
    title: "Junior Web Designer",
    noOfBid: "10",
    amount: "₵2000 - ₵3000",
    skills: [
      "ux writing",
      "wire framing",
      "prototyping",
      "information architecture",
    ],
  },
];
