export const POSTJOBFIELD = {
  fieldDetail: [
    {
      id: 1,
      name: "job_title",
      label: "Job Title",
      type: "text",
      placeholder: "Data Analysis Expert",
      icon: "fs-input-icon fa fa-address-card",
      box: "ls-inputicon-box",
    },
    {
      id: 2,
      name: "job_category_id",
      label: "Job Category",
      type: "text",
      options: [
        { id: 1, name: "Graphic Design" },
        { id: 2, name: "Video Production" },
        { id: 3, name: "Programming" },
        { id: 4, name: "Hospitability" },
        { id: 5, name: "Catering" },
      ],
      icon: "fs-input-icon fa fa-border-all",
      box: "ls-inputicon-box",
    },
    {
      id: 3,
      name: "job_type",
      label: "Job Type",
      type: "text",
      options: [
        { id: 1, name: "Full Time" },
        { id: 2, name: "Freelance" },
        { id: 3, name: "Part Time" },
        { id: 4, name: "Internship" },
        { id: 5, name: "Temporary" },
      ],
      icon: "fs-input-icon fa fa-border-all",
      box: "ls-inputicon-box",
    },
    {
      id: 4,
      name: "salary",
      label: "Offered salary",
      type: "text",
      placeholder: "Salary",
      icon: "fs-input-icon fa fa-dollar-sign",
      box: "ls-inputicon-box",
    },
    {
      id: 5,
      name: "experience",
      label: "Experience",
      type: "text",
      placeholder: "Eg Minimum 3 years",
      icon: "fs-input-icon fa fa-user-edit",
      box: "ls-inputicon-box",
    },
    {
      id: 6,
      name: "qualification",
      label: "Qualification",
      type: "text",
      placeholder: "Qualification Title",
      icon: "fs-input-icon fa fa-user-graduate",
      box: "ls-inputicon-box",
    },
    {
      id: 7,
      name: "budget",
      label: "Budget",
      type: "text",
      placeholder: "200",
      icon: "fs-input-icon fa fa-dollar-sign",
      box: "ls-inputicon-box",
    },

    {
      id: 8,
      name: "skills_id",
      label: "Skills",
      type: "text",
      placeholder: "Writer, Graphic Design",
      icon: "fs-input-icon fa fa-map-pin",
      box: "ls-inputicon-box",
    },

    {
      id: 9,
      name: "duty",
      label: "Duty",
      type: "text",
      placeholder: "Duty",
      icon: "fs-input-icon fa fa-map-pin",
      box: "ls-inputicon-box",
    },

    {
      id: 10,
      name: "description",
      label: "Description (Skills Required)",
      type: "text",
      placeholder: "We are doing well",
      icon: "fs-input-icon fa fa-map-pin",
      box: "ls-inputicon-box",
    },
    {
      id: 11,
      name: "start_date",
      label: "Start Date",
      type: "date",
      placeholder: "dd/mm/yyyy",
      icon: "fs-input-icon far fa-calendar",
      box: "ls-inputicon-box",
    },
    {
      id: 12,
      name: "end_date",
      label: "End Date",
      type: "date",
      placeholder: "dd/mm/yyyy",
      icon: "fs-input-icon far fa-calendar",
      box: "ls-inputicon-box",
    },
  ],
};
