export const countryData = {
  "Greater Accra": ["Adabraka", "Accra", "Tema", "Madina"],
  Ashanti: ["Kumasi", "Obuasi"],
  Western: ["Takoradi", "Sekondi"],
  Eastern: ["Koforidua", "Akosombo"],
  Central: ["Cape Coast", "Winneba"],
  Volta: ["Ho", "Keta"],
  Northern: ["Tamale", "Yendi"],
  "Upper East": ["Bolgatanga", "Bawku"],
  "Upper West": ["Wa", "Lawra"],
  Bono: ["Sunyani", "Dormaa Ahenkro"],
  "Bono East": ["Techiman", "Kintampo"],
  Ahafo: ["Goaso", "Mim"],
  "Western North": ["Sefwi Wiawso", "Bibiani"],
  Oti: ["Dambai", "Jasikan"],
  "North East": ["Nalerigu", "Walewale"],
  Savannah: ["Damongo", "Salaga"],
};
