export const courses = [
    "Accounting",
    "Actuarial Science",
    "Agricultural Engineering",
    "Agriculture",
    "Architecture",
    "Banking and Finance",
    "Biomedical Engineering",
    "Biochemistry",
    "Business Administration",
    "Chemical Engineering",
    "Civil Engineering",
    "Computer Engineering",
    "Computer Science",
    "Construction Technology and Management",
    "Creative Arts",
    "Criminology",
    "Development Studies",
    "Dentistry",
    "Economics",
    "Education (Various Specializations)",
    "Electrical Engineering",
    "Environmental Science",
    "Entrepreneurship",
    "Fashion and Textile Design",
    "Film and Theatre Arts",
    "Fisheries and Aquatic Science",
    "Food Science and Technology",
    "Forestry",
    "Geography and Resource Development",
    "Geology",
    "Graphic Design",
    "Health Administration and Management",
    "Hospitality and Tourism Management",
    "Human Resource Management",
    "Industrial Art",
    "Information Technology",
    "Insurance",
    "International Relations",
    "Journalism and Mass Communication",
    "Land Economy",
    "Law",
    "Linguistics",
    "Marketing",
    "Mathematics",
    "Mechanical Engineering",
    "Medical Laboratory Science",
    "Medicine and Surgery (MBChB)",
    "Metallurgical and Materials Engineering",
    "Midwifery",
    "Mining Engineering",
    "Music",
    "Nursing",
    "Nutrition and Dietetics",
    "Optometry",
    "Petroleum Engineering",
    "Pharmacy",
    "Philosophy and Religious Studies",
    "Physics",
    "Political Science",
    "Psychology",
    "Public Administration",
    "Public Health",
    "Quantity Surveying and Construction Economics",
    "Real Estate Management",
    "Social Work",
    "Sociology",
    "Special Education",
    "Statistics",
    "Surveying and Geomatics",
    "Theology and Biblical Studies",
    "Veterinary Medicine",
    "Visual Arts",
    "Water and Sanitation Engineering",
    "Zoology"
  ];
  