export const professions = [
    "Accountant",
    "Actor",
    "Actuary",
    "Agricultural Engineer",
    "Agricultural Extension Officer",
    "Air Traffic Controller",
    "Architect",
    "Artist",
    "Auditor",
    "Auto Mechanic",
    "Banker",
    "Barber",
    "Bartender",
    "Biomedical Scientist",
    "Constructor",
    "Broadcast Journalist",
    "Business Analyst",
    "Carpenter",
    "Cashier",
    "Chef",
    "Civil Engineer",
    "Cleaner",
    "Clinical Psychologist",
    "Computer Engineer",
    "Construction Manager",
    "Customer Service Representative",
    "Data Analyst",
    "Data Scientist",
    "Dentist",
    "Doctor",
    "Driver",
    "Economist",
    "Electrical Engineer",
    "Electrician",
    "Entrepreneur",
    "Environmental Scientist",
    "Event Planner",
    "Fashion Designer",
    "Farmer",
    "Financial Analyst",
    "Firefighter",
    "Fisherman",
    "Flight Attendant",
    "Front-end Developer",
    "Geologist",
    "Graphic Designer",
    "Hairdresser",
    "Human Resource Manager",
    "ICT Specialist",
    "Insurance Broker",
    "Interior Designer",
    "Journalist",
    "Judge",
    "Lab Technician",
    "Lawyer",
    "Lecturer",
    "Logistics Manager",
    "Makeup Artist",
    "Marketing Manager",
    "Mechanical Engineer",
    "Midwife",
    "Military Personnel",
    "Miner",
    "Music Producer",
    "Musician",
    "Nurse",
    "Nutritionist",
    "Painter",
    "Paramedic",
    "Pharmacist",
    "Photographer",
    "Physician",
    "Physiotherapist",
    "Pilot",
    "Plumber",
    "Police Officer",
    "Politician",
    "Primary School Teacher",
    "Procurement Officer",
    "Professor",
    "Project Manager",
    "Psychologist",
    "Real Estate Agent",
    "Research Scientist",
    "Retail Worker",
    "Sales Executive",
    "Social Media Manager",
    "Social Worker",
    "Software Developer",
    "Software Engineer",
    "Sound Engineer",
    "Sports Coach",
    "Statistician",
    "Surveyor",
    "Tailor",
    "Taxi Driver",
    "Teacher",
    "Technical Support Engineer",
    "Trader",
    "Travel Agent",
    "TV/Radio Presenter",
    "UX Designer",
    "Veterinarian",
    "Waiter",
    "Welder",
    "Writer"
  ];
  