export const staff_data = [
  {
    id: 1,
    staff_name: "Heli Karma",
    position: "Developer",
    job_type: "Part Time",
    start_date: "12th Jan, 2025",
    salary_type: "fixed",
    team: "No Team",
    salary: 200,
    job_apply_id: 1,
  },
  {
    id: 2,
    staff_name: "Heli Karma",
    position: "Developer",
    job_type: "Full Time",
    start_date: "12th Jan, 2025",
    salary_type: "fixed",
    team: "Graphics Team",
    salary: 200,
    job_apply_id: 1,
  },
  {
    id: 3,
    staff_name: "Heli Karma",
    position: "Developer",
    job_type: "Full Time",
    start_date: "12th Jan, 2025",
    salary_type: "fixed",
    team: "Software Team",
    salary: 200,
    job_apply_id: 1,
  },
  {
    id: 4,
    staff_name: "Heli Karma",
    position: "Developer",
    job_type: "Full Time",
    start_date: "12th Jan, 2025",
    salary_type: "fixed",
    team: "No Team",
    salary: 200,
    job_apply_id: 1,
  },
];
